### ISSUE TITLE
SDR paper

### ISSUE THREAD

**Issue by breznak** [numenta/nupic.research#114]
[sdr_paper](https://github.com/numenta/nupic.research/tree/master/sdr_paper) mentions a [SDR paper](http://numenta.com/assets/pdf/whitepapers/SDR_Properties%20draft%2010-28-14.pdf) is this the latest version? and are there .tex files for the paper?

**Comment by breznak** [comment]
CC @subutai

**Comment by subutai** [comment]
@breznak We are writing a version of that same paper for a journal. Unfortunately due to journal submission restrictions we can't release that until after it is published. However the core content is very similar to the paper you mentioned.  sdr_paper includes some initial simulations of the equations in there - we'll do some more over the next couple of weeks.

**Comment by breznak** [comment]
:+1: thanks, looking forward for a good read :wink:

**Comment by subutai** [comment]
Thanks! Don't hold you breath though - I'm still in an early draft stage. Journal review cycles can be really long!  For now, I think [my talk](http://numenta.com/learn/sparse-distributed-representations.html) is the best reference for this work.
