### ISSUE TITLE
Port bug fixes in temporal_memory_phases to new temporal_memory

### ISSUE THREAD

**Issue by subutai** [numenta/nupic.research#603]
Some changes have been made to temporal_memory_phases. This issue is to review the various commits and ensure they are ported to the new temporal memory implementations.  This is related to https://github.com/numenta/nupic/issues/3268 but this issue is there just in case there are additional changes.

**Comment by oxtopus** [comment]
I believe this is done.  `TemporalMemory._burstColumn()` and `TemporalMemory._growSynapses()` appropriately reconcile differences between the desired number and actually available.  I don't see any other bug fixes that have since been applied to `temporal_memory_phases.py` that should otherwise be applied to the new temporal memory.
